### ISSUE TITLE
Fen's NPC Portrait Workaround v2.2.2 VS Browser

### ISSUE THREAD

**Issue by SpencerGresoro** [bakermd86/FoogleBrowser#6]
Hi SirNoob,

I sent a message in FG forums, but its just much easier here. When NPC portraits is enabled, I get a pretty bad runtime when dragging an npc record onto the Combat Tracker. It forces me to restart the client. No amount of rebuilding will work (aka it will stay in a broken state after this happens). Attached are some images and log files (ZIpped).

![image](https://user-images.githubusercontent.com/18724865/235814663-55b018af-26d8-4db5-b9cb-c537a39e6cef.png)
![image](https://user-images.githubusercontent.com/18724865/235814670-65587c3f-0abe-4a50-983e-ecb0addd7c24.png)

[fgu_logs_20230502.zip](https://github.com/bakermd86/FoogleBrowser/files/11378644/fgu_logs_20230502.zip)

**Comment by bakermd86** [comment]
Looks like an issue with processing records that are created, modified then deleted before the indexing is able to scan them.

It happens because the NPC portrait workaround creates a dummy character sheet record for NPCs, sets their portrait, then deletes them. I do that because it is the only way to get the FG client to create the portrait so that it can be linked in chat.

But that causes an error from the DB API when trying to index the modified node. I added some error handling that should prevent it here:

https://github.com/bakermd86/FoogleBrowser/releases/tag/v1.2.3a1

If you want to give it a try and let me know, I can push it to the forge if it fixes the issue for you.

**Comment by SpencerGresoro** [comment]
This seems ok - although I have noticed it runtime a few times since the last update. Error on 'getChildNode' (or something like this, wish i had my laptop right now to send it) Its weird. I couldn't pin it done. I'd push this though, it definitely fixed the issue I was first experiencing. :)
